spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auto_posting?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
server:
  port: 8081
